from .environment import env


class Braintree(object):
    BRAINTREE_USE_SANDBOX = env('BRAINTREE_USE_SANDBOX')
    BRAINTREE_MERCHANT_ID = env('BRAINTREE_MERCHANT_ID')
    BRAINTREE_PUBLIC_KEY = env('BRAINTREE_PUBLIC_KEY')
    BRAINTREE_PRIVATE_KEY = env('BRAINTREE_PRIVATE_KEY')
    BRAINTREE_TOKENIZATION_KEY = env('BRAINTREE_TOKENIZATION_KEY')
    BRAINTREE_MERCHANT_ACCOUNTS = env('BRAINTREE_MERCHANT_ACCOUNTS')
    BRAINTREE_PLANS = env('BRAINTREE_PLANS')
    BRAINTREE_MERCHANT_ACCOUNTS_PAYPAL_MICRO = env('BRAINTREE_MERCHANT_ACCOUNTS_PAYPAL_MICRO')

    @property
    def BRAINTREE_PARAMS(self):
        return {
            'use_sandbox': self.BRAINTREE_USE_SANDBOX,
            'token': self.BRAINTREE_TOKENIZATION_KEY,
        }
