LANGUAGES = [
    ('ach', 'Acholi'),
    ('ar', 'Arabic'),
    ('ast', 'Asturian'),
    ('az', 'Azerbaijani'),
    ('bn', 'Bengali'),
    ('bs', 'Bosnian'),
    ('ca', 'Catalan'),
    ('cs', 'Czech'),
    ('cy', 'Welsh'),
    ('da', 'Danish'),
    ('de', 'German'),
    ('dsb', 'Sorbian, Lower'),
    ('el', 'Greek'),
    ('en-US', 'English (US)'),
    ('en-AU', 'English (Australia)'),
    ('en-CA', 'English (Canada)'),
    ('en-GB', 'English (Great Britain)'),
    ('en-IN', 'English (India)'),
    ('en-NZ', 'English (New Zealand)'),
    ('es', 'Spanish'),
    ('es-MX', 'Spanish (Mexico)'),
    ('es-XL', 'Spanish (Latin America)'),
    ('et', 'Estonian'),
    ('fr', 'French'),
    ('fy-NL', 'Frisian'),
    ('gu-IN', 'Gujarati'),
    ('he', 'Hebrew'),
    ('hi-IN', 'Hindi'),
    ('hr', 'Croatian'),
    ('hsb', 'Sorbian, Upper'),
    ('hu', 'Hungarian'),
    ('ia', 'Interlingua'),
    ('id', 'Indonesian'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('ka', 'Georgian'),
    ('kab', 'Kabyle'),
    ('ko', 'Korean'),
    ('lg', 'Luganda'),
    ('lo', 'Lao'),
    ('lv', 'Latvian'),
    ('ml', 'Malayalam'),
    ('mr', 'Marathi'),
    ('nb-NO', 'Norwegian Bokmål'),
    ('nl', 'Dutch'),
    ('nn-NO', 'Norwegian Nynorsk'),
    ('pl', 'Polish'),
    ('pt-BR', 'Portuguese (Brazil)'),
    ('pt-PT', 'Portuguese (Portugal)'),
    ('pa-IN', 'Punjabi'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('sq', 'Albanian'),
    ('sv-SE', 'Swedish'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('th', 'Thai'),
    ('tr', 'Turkish'),
    ('uk', 'Ukrainian'),
    ('uz', 'Uzbek'),
    ('vi', 'Vietnamese'),
    ('zh-CN', 'Chinese (China)'),
    ('zh-TW', 'Chinese (Taiwan)'),
]

# Collection of different language email templates,
# for receipt sending through acoustic in payments/tasks.py.
LANGUAGE_IDS = {
    "ja": "2960734",
    "pl": "2959660",
    "pt-BR": "2960746",
    "cs": "2960691",
    "de": "2960705",
    "es": "2960719",
    "fr": "2960725",
    "en-US": "2959686",
}
