pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - "#approved-reviews-by>=1"
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
    actions:
      merge:
        method: squash
        strict_method: rebase
        strict: true
  - name: Automatic merge for PRs labelled "ready to merge"
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        strict_method: rebase
        strict: true
