queue_rules:
  - name: dependabot
    conditions:
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"

  - name: ready-to-merge
    conditions:
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"

pull_request_rules:
  - name: Automatic merge for dependabot PRs
    conditions:
      - "#approved-reviews-by>=1"
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
    actions:
      queue:
        method: squash
        name: dependabot

  - name: Automatic merge for PRs labelled "ready to merge"
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=continuous-integration/travis-ci/pr"
      - "status-success=continuous-integration/travis-ci/push"
      - "label=ready-to-merge"
    actions:
      queue:
        method: squash
        name: ready-to-merge
