dist: xenial
language: python
python: '3.7'
addons:
  postgresql: '10'
env:
  global:
  - ALLOWED_HOSTS=localhost
  - CONTENT_TYPE_NO_SNIFF=True
  - DATABASE_URL=postgres://postgres@localhost:5432/donate
  - DEBUG=False
  - DJANGO_SECRET_KEY=secret
  - SET_HSTS=False
  - SSL_REDIRECT=False
  - USE_S3=False
  - X_FRAME_OPTIONS=DENY
  - XSS_PROTECTION=True
  - secure: Pq+Po/RH+KPTCtY2XMYbJC0r3d13xlGvZdBhPUIH/9GCwJAor4Xzdc3xD5Hat+I6dv/uH0uSa1fo171u5qSYy/1okRho4hA/tQZvqjTmqtNW7n+CpbgqLpbOiSil5In9ch0qXeoYDjY/3H3f99U8gqFoJBhLhFd8XPUvmCrsIodi+5WvLJjqjbsVl/DvLKa1kbxtPqxVxIoqn1/u+nAX2l4fxwTABztKW3d5NmQlpRHvy+vt7ql8vrRu2UQUldC6uVbYQP5Wtrz1AErAaZ9YyhDWcIvmm1b/IhEXpp6cpPxULqJQViEkDbVsOHVsWahZTN2d2tO4QX8fXUu8LBFgqr19JS46xDDlqQLXHWQefDQIXVXQrENaMXmJheqHuNcGRvIpxfRb9Hcx1V8EpbtA3ZTgoNoeqNC6zoShcjEePdEKSOlNAwQ0lU07eWO7mNjwYtcpXPLcs//JNZSW0+z5MrXFlrG6YNfFN42TvtlAuii7UGDEHIdmyhMG39FPMzLHVxEuNnM6jPpCYY/irQL0eBInoV4Qu9oqP4MwGxkrjeuSEYEUawpgSBWDDpp+gMmVimf7cejLxuBZ4sBfUcrsG1Vy092j2NOBv92DoZVeaR+bmfk1eHyTJhBjGlRtUeVlNPVOVa9lEaJe1S3zOrWDN2z8omPslxp89BPNiUbERh4=

cache:
  pip: true
  directories:
  - "$HOME/.npm"
matrix:
  include:
  - name: Python tests
    install: "./travis-scripts/python-install.sh"
    before_script:
    - psql -c 'create database donate;' -U postgres
    script:
    - flake8 donate/
    - coverage run --source './donate' ./manage.py test --settings=donate.settings --configuration=Testing
    after_success:
    - coveralls
  - name: npm tests
    before_install:
    - nvm install 14.4
    - nvm use 14.4
    install: "./travis-scripts/npm-install.sh"
    script: npm run test

