# Generated by Django 2.2.13 on 2020-11-10 12:57

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import donate.core.blocks
import modelcluster.fields
import uuid
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# donate.core.migrations.0011_refactor_accordion_block

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_campaignpage_campaignpagedonationamount'), ('core', '0003_auto_20190724_0853'), ('core', '0004_campaignpage_intro'), ('core', '0005_auto_20190808_0529'), ('core', '0006_contentpage'), ('core', '0007_wagtail_localize_1'), ('core', '0008_wagtail_localize_2'), ('core', '0009_wagtail_localize_3'), ('core', '0010_auto_20191007_1308'), ('core', '0011_refactor_accordion_block'), ('core', '0012_contributorsupportpage'), ('core', '0013_auto_20200225_1140'), ('core', '0014_auto_20200813_1441'), ('core', '0015_remove_old_wagtail_localize')]

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('lead_text', models.CharField(max_length=800)),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
                ('intro', wagtail.core.fields.RichTextField()),
                ('campaign_id', models.CharField(blank=True, help_text='Used for analytics and reporting', max_length=255)),
                ('project', models.CharField(choices=[('mozillafoundation', 'Mozilla Foundation'), ('thunderbird', 'Thunderbird')], default='mozillafoundation', help_text='The project that donations from this campaign should be associated with', max_length=25)),
                ('translation_key', models.UUIDField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CampaignPageDonationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'USD   $'), ('aed', 'AED   د.إ.\u200f'), ('all', 'ALL   L'), ('aud', 'AUD   $'), ('ars', 'ARS   $'), ('azn', 'AZN   ₼'), ('bam', 'BAM   KM'), ('bdt', 'BDT   ৳'), ('brl', 'BRL   R$'), ('cad', 'CAD   $'), ('chf', 'CHF   Fr.'), ('clp', 'CLP   $'), ('cny', 'CNY   ¥'), ('czk', 'CZK   Kč'), ('dkk', 'DKK   kr'), ('dzd', 'DZD   د.ج.\u200f'), ('egp', 'EGP   ج.م.\u200f'), ('eur', 'EUR   €'), ('gbp', 'GBP   £'), ('gel', 'GEL   ₾'), ('gtq', 'GTQ   Q'), ('hkd', 'HKD   $'), ('hrk', 'HRK   kn'), ('huf', 'HUF   Ft'), ('idr', 'IDR   Rp'), ('ils', 'ILS   ₪'), ('inr', 'INR   ₹'), ('jpy', 'JPY   ¥'), ('krw', 'KRW   ₩'), ('lak', 'LAK   ₭'), ('lbp', 'LBP   ل.ل.\u200e'), ('mad', 'MAD   MAD'), ('myr', 'MYR   RM'), ('mxn', 'MXN   $'), ('nok', 'NOK   kr'), ('nzd', 'NZD   $'), ('php', 'PHP   ₱'), ('pln', 'PLN   zł'), ('qar', 'QAR   ر.ق.\u200f'), ('ron', 'RON   lei'), ('rub', 'RUB   ₽'), ('sar', 'SAR   ر.س.\u200f'), ('sek', 'SEK   kr'), ('sgd', 'SGD   $SG'), ('thb', 'THB   ฿'), ('try', 'TRY   ₺'), ('twd', 'TWD   NT$'), ('uah', 'UAH   ₴'), ('yer', 'YER   ر.ي.\u200f'), ('zar', 'ZAR   R')], db_index=True, max_length=3)),
                ('single_options', wagtail.core.fields.StreamField([('amount', wagtail.core.blocks.DecimalBlock(decimal_places=2, max_digits=7, min_value=0))])),
                ('monthly_options', wagtail.core.fields.StreamField([('amount', wagtail.core.blocks.DecimalBlock(decimal_places=2, max_digits=7, min_value=0))])),
                ('campaign', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_amounts', to='core.CampaignPage')),
            ],
            options={
                'unique_together': {('campaign', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField()),
                ('featured_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
                ('campaign_id', models.CharField(blank=True, help_text='Used for analytics and reporting', max_length=255)),
                ('project', models.CharField(choices=[('mozillafoundation', 'Mozilla Foundation'), ('thunderbird', 'Thunderbird')], default='mozillafoundation', help_text='The project that donations from this campaign should be associated with', max_length=25)),
                ('translation_key', models.UUIDField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('call_to_action_text', models.CharField(blank=True, max_length=255)),
                ('call_to_action_url', models.URLField(blank=True)),
                ('body', wagtail.core.fields.StreamField([('heading', donate.core.blocks.HeadingBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('accordion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.ListBlock(donate.core.blocks.AccordionItem))]))])),
                ('translation_key', models.UUIDField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', donate.core.blocks.HeadingBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('accordion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.StreamBlock([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link']))]))]))]))]),
        ),
        migrations.AlterField(
            model_name='campaignpagedonationamount',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD   $'), ('aed', 'AED   د.إ.\u200f'), ('aud', 'AUD   $'), ('ars', 'ARS   $'), ('azn', 'AZN   ₼'), ('bam', 'BAM   KM'), ('bdt', 'BDT   ৳'), ('brl', 'BRL   R$'), ('cad', 'CAD   $'), ('chf', 'CHF   Fr.'), ('clp', 'CLP   $'), ('cny', 'CNY   ¥'), ('czk', 'CZK   Kč'), ('dkk', 'DKK   kr'), ('dzd', 'DZD   د.ج.\u200f'), ('egp', 'EGP   ج.م.\u200f'), ('eur', 'EUR   €'), ('gbp', 'GBP   £'), ('gel', 'GEL   ₾'), ('gtq', 'GTQ   Q'), ('hkd', 'HKD   $'), ('hrk', 'HRK   kn'), ('huf', 'HUF   Ft'), ('idr', 'IDR   Rp'), ('ils', 'ILS   ₪'), ('inr', 'INR   ₹'), ('jpy', 'JPY   ¥'), ('krw', 'KRW   ₩'), ('lak', 'LAK   ₭'), ('lbp', 'LBP   ل.ل.\u200e'), ('mad', 'MAD   MAD'), ('myr', 'MYR   RM'), ('mxn', 'MXN   $'), ('nok', 'NOK   kr'), ('nzd', 'NZD   $'), ('php', 'PHP   ₱'), ('pln', 'PLN   zł'), ('qar', 'QAR   ر.ق.\u200f'), ('ron', 'RON   lei'), ('rub', 'RUB   ₽'), ('sar', 'SAR   ر.س.\u200f'), ('sek', 'SEK   kr'), ('sgd', 'SGD   $SG'), ('thb', 'THB   ฿'), ('try', 'TRY   ₺'), ('twd', 'TWD   NT$'), ('uah', 'UAH   ₴'), ('yer', 'YER   ر.ي.\u200f'), ('zar', 'ZAR   R')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='campaignpagedonationamount',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD   $'), ('aud', 'AUD   $'), ('brl', 'BRL   R$'), ('cad', 'CAD   $'), ('chf', 'CHF   Fr.'), ('czk', 'CZK   Kč'), ('dkk', 'DKK   kr'), ('eur', 'EUR   €'), ('gbp', 'GBP   £'), ('hkd', 'HKD   $'), ('huf', 'HUF   Ft'), ('inr', 'INR   ₹'), ('jpy', 'JPY   ¥'), ('mxn', 'MXN   $'), ('nok', 'NOK   kr'), ('nzd', 'NZD   $'), ('pln', 'PLN   zł'), ('rub', 'RUB   ₽'), ('sek', 'SEK   kr'), ('twd', 'TWD   NT$')], db_index=True, max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='campaignpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='translation_key',
        ),
        migrations.CreateModel(
            name='ContributorSupportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='translation_key',
        ),
    ]
