# Generated by Django 3.1.11 on 2021-11-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('core', '0001_squashed_0015_remove_old_wagtail_localize'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_paypal', models.BooleanField(default=False, verbose_name='Enable the PayPal button on the donate form')),
                ('enable_recaptcha', models.BooleanField(default=True, verbose_name='Enable recaptcha across the site')),
                ('use_checkbox_recaptcha', models.BooleanField(default=True, verbose_name='Use a checkbox recaptcha on the CC donate form')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
