# Generated by Django 2.2.3 on 2019-07-11 08:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('lead_text', models.CharField(max_length=800)),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CampaignPageDonationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('aed', 'aed'), ('all', 'all'), ('aud', 'aud'), ('ars', 'ars'), ('azn', 'azn'), ('bam', 'bam'), ('bdt', 'bdt'), ('brl', 'brl'), ('cad', 'cad'), ('chf', 'chf'), ('clp', 'clp'), ('cny', 'cny'), ('czk', 'czk'), ('dkk', 'dkk'), ('dzd', 'dzd'), ('egp', 'egp'), ('eur', 'eur'), ('gbp', 'gbp'), ('gel', 'gel'), ('gtq', 'gtq'), ('hkd', 'hkd'), ('hrk', 'hrk'), ('huf', 'huf'), ('idr', 'idr'), ('ils', 'ils'), ('inr', 'inr'), ('jpy', 'jpy'), ('krw', 'krw'), ('lak', 'lak'), ('lbp', 'lbp'), ('mad', 'mad'), ('myr', 'myr'), ('mxn', 'mxn'), ('nok', 'nok'), ('nzd', 'nzd'), ('php', 'php'), ('pln', 'pln'), ('qar', 'qar'), ('ron', 'ron'), ('rub', 'rub'), ('sar', 'sar'), ('sek', 'sek'), ('sgd', 'sgd'), ('thb', 'thb'), ('try', 'try'), ('twd', 'twd'), ('uah', 'uah'), ('yer', 'yer'), ('zar', 'zar')], db_index=True, max_length=3)),
                ('single_1', models.DecimalField(decimal_places=2, max_digits=7)),
                ('single_2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('single_3', models.DecimalField(decimal_places=2, max_digits=7)),
                ('single_4', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monthly_1', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monthly_2', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monthly_3', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monthly_4', models.DecimalField(decimal_places=2, max_digits=7)),
                ('campaign', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_amounts', to='core.CampaignPage')),
            ],
            options={
                'unique_together': {('campaign', 'currency')},
            },
        ),
    ]
