# Generated by Django 3.1.14 on 2023-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='cta_first',
            field=models.BooleanField(default=False, help_text='Check this to shift the CTA to the left on desktop and to the top on mobile.'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='donate_form_header',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='intro_header',
            field=models.CharField(blank=True, default='Donate now', max_length=200),
        ),
    ]
