# Generated by Django 3.1.11 on 2021-11-23 19:21

from django.db import migrations, models
import django.db.models.deletion


def create_default_feature_flags(apps, schema_editor):
    Site = apps.get_model("wagtailcore", "Site")
    default_site = Site.objects.get(is_default_site=True)
    FeatureFlags = apps.get_model("core", "FeatureFlags")
    if FeatureFlags.objects.all().count() == 0:
        FeatureFlags.objects.create(site=default_site)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_featureflags'),
    ]

    operations = [
        migrations.RunPython(
            code=create_default_feature_flags,
        ),
    ]
