# Generated by Django 2.2.3 on 2019-07-26 07:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190724_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
