# Generated by Django 2.2.4 on 2019-08-05 10:59

from django.db import migrations
from wagtail_localize.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wagtail_localize_1'),
    ]

    operations = [
        # This sets the translation_key field to a unique value for each page
        BootstrapTranslatableModel('core.LandingPage'),
        BootstrapTranslatableModel('core.CampaignPage'),
        BootstrapTranslatableModel('core.ContentPage'),
    ]
