# Generated by Django 2.2.4 on 2019-08-05 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_localize.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wagtail_localize_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='campaignpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='campaignpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together={('translation_key', 'locale')},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='locale',
            field=models.ForeignKey(default=wagtail_localize.models.default_locale_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_localize.Locale'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together={('translation_key', 'locale')},
        ),
    ]
