# Generated by Django 2.2.6 on 2019-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wagtail_localize_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='is_source_translation',
            field=models.BooleanField(default=True),
        ),
    ]
