# Generated by Django 2.2.6 on 2019-11-13 02:29
import json
from django.db import migrations
import donate.core.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


def empty_old_accordions(apps, schema_editor):
    ContentPage = apps.get_model('core', 'ContentPage')
    # Clear all existing accordions from the page because we've changed their
    # block structure, and the editor will not handle this gracefully.
    for p in ContentPage.objects.all():
        data = p.body.stream_data
        new_data = [block for block in data if not block['type'] == 'accordion']
        p.body = json.dumps(new_data)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191007_1308'),
    ]

    operations = [
        migrations.RunPython(empty_old_accordions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', donate.core.blocks.HeadingBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('accordion', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('items', wagtail.core.blocks.StreamBlock([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link']))]))]))]))]),
        ),
    ]
