# Generated by Django 2.2.9 on 2020-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contributorsupportpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpagedonationamount',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD   $'), ('aed', 'AED   د.إ.\u200f'), ('aud', 'AUD   $'), ('ars', 'ARS   $'), ('azn', 'AZN   ₼'), ('bam', 'BAM   KM'), ('bdt', 'BDT   ৳'), ('brl', 'BRL   R$'), ('cad', 'CAD   $'), ('chf', 'CHF   Fr.'), ('clp', 'CLP   $'), ('cny', 'CNY   ¥'), ('czk', 'CZK   Kč'), ('dkk', 'DKK   kr'), ('dzd', 'DZD   د.ج.\u200f'), ('egp', 'EGP   ج.م.\u200f'), ('eur', 'EUR   €'), ('gbp', 'GBP   £'), ('gel', 'GEL   ₾'), ('gtq', 'GTQ   Q'), ('hkd', 'HKD   $'), ('hrk', 'HRK   kn'), ('huf', 'HUF   Ft'), ('idr', 'IDR   Rp'), ('ils', 'ILS   ₪'), ('inr', 'INR   ₹'), ('jpy', 'JPY   ¥'), ('krw', 'KRW   ₩'), ('lak', 'LAK   ₭'), ('lbp', 'LBP   ل.ل.\u200e'), ('mad', 'MAD   MAD'), ('myr', 'MYR   RM'), ('mxn', 'MXN   $'), ('nok', 'NOK   kr'), ('nzd', 'NZD   $'), ('php', 'PHP   ₱'), ('pln', 'PLN   zł'), ('qar', 'QAR   ر.ق.\u200f'), ('ron', 'RON   lei'), ('rub', 'RUB   ₽'), ('sar', 'SAR   ر.س.\u200f'), ('sek', 'SEK   kr'), ('sgd', 'SGD   $SG'), ('thb', 'THB   ฿'), ('try', 'TRY   ₺'), ('twd', 'TWD   NT$'), ('uah', 'UAH   ₴'), ('yer', 'YER   ر.ي.\u200f'), ('zar', 'ZAR   R')], db_index=True, max_length=3),
        ),
    ]
