# Generated by Django 2.2.12 on 2020-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200225_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpagedonationamount',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD   $'), ('aud', 'AUD   $'), ('brl', 'BRL   R$'), ('cad', 'CAD   $'), ('chf', 'CHF   Fr.'), ('czk', 'CZK   Kč'), ('dkk', 'DKK   kr'), ('eur', 'EUR   €'), ('gbp', 'GBP   £'), ('hkd', 'HKD   $'), ('huf', 'HUF   Ft'), ('inr', 'INR   ₹'), ('jpy', 'JPY   ¥'), ('mxn', 'MXN   $'), ('nok', 'NOK   kr'), ('nzd', 'NZD   $'), ('pln', 'PLN   zł'), ('rub', 'RUB   ₽'), ('sek', 'SEK   kr'), ('twd', 'TWD   NT$')], db_index=True, max_length=3),
        ),
    ]
