# Generated by Django 2.2.13 on 2020-11-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200813_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contributorsupportpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='campaignpage',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='contributorsupportpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='contributorsupportpage',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='contributorsupportpage',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='is_source_translation',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='translation_key',
        ),
    ]
