# Generated by Django 2.2.2 on 2019-06-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='footer_links',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='footer_navigation',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='secondary_navigation',
        ),
    ]
